### PR TITLE
Add step to install ffmpeg in Dockerfile

### LINKED ISSUE #10: Dockerfile is missing the step to install ffmpeg
I had to run these extra commands to get ffmpeg (for converting to wav)
```
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
yum install ffmpeg
```

### PR DESCRIPTION
**Pull request by tran2**
Also updated instructions to use docker
Resolves #10

### CODE REVIEW

**Comment by antoniomo** [comment]
Looks good to me! Please add yourself to the authors on the Dockerfile and also to Contributors at the end of the README, something like:

```
Brendan Cunnie (@saintbrendan, saintbrendan@gmail.com) and Brian Cunnie (@cunnie, brian.cunnie@gmail.com) contributed the Dockerfile. <Your name and email and/or github handle> added ffmpeg to it to support non-wav files.
```

**Comment by tran2** [comment]
@antoniomo, I have added myself as Dockerfile author and updated the readme as suggested. Thank you!

**Comment by antoniomo** [comment]
Perfect, thanks!!

**Comment by antoniomo** [comment]
Hi! Please note issue #13, let me know if you are still interesting in keeping that Dockerfile up to date. As you know this project is on maintenance-only so I don't expect that many changes are needed in the future :)

**Comment by antoniomo** [comment]
Maybe I'll quote @tran2 in case the above message didn't go through :)

**Comment by tran2** [comment]
@antoniomo ah my bad yea I can keep it up to date

**Comment by antoniomo** [comment]
Nice, thanks!

**Pull request merged**
